In [1]:
import numpy as np

In [2]:
# Question 1
arr = np.array([-9,-7,-5,-3,1,4,6,8,9])
arr

array([-9, -7, -5, -3,  1,  4,  6,  8,  9])

In [3]:
# Question 2
D = np.array(range(18)) + 3

In [4]:
D

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20])

In [5]:
# Q2[a]
x = D[2:11]

In [6]:
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13])

In [7]:
# Q2(b)
y = x[::-1]

In [8]:
y

array([13, 12, 11, 10,  9,  8,  7,  6,  5])

In [9]:
# Q2(c)
z = D[::-1]
z

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,
        3])

In [10]:
# Question 3

# Numpy array consumes less memory than list
# Numpy array is fast than python list
# Numpy array is convenient to use

In [ ]:
# Question 4

# numpy.bool_  : Boolean(True or False)
# numpy.byte   : signed character
# numpy.ubyte  : unsigned character
# numpy.intc   : integer
# numpy.int_   : long
# numpy.single : float
# numpy.double : double